@extends('layouts.admin')
@section('title','Test Batches')
@section('content')
<div class="card"><div class="card-header"><div class="card-title">Test Batch Management</div><button class="btn btn-primary" onclick="openModal('addB')">＋ Create Test Batch</button></div><table><thead><tr><th>Batch Title</th><th>Category</th><th>Tests</th><th>Validity</th><th>Price</th><th>Status</th><th>Action</th></tr></thead><tbody>@foreach($batches as $b)<tr><td>{{ $b->title }}</td><td>{{ $b->category->name??'All' }}</td><td>{{ $b->tests_count }}</td><td>{{ $b->validity_days }} Days</td><td>₹{{ number_format($b->price,2) }}</td><td>{{ ucfirst($b->status) }}</td><td><a class="icon-btn edit" href="{{ route('admin.testengine.access',$b) }}">👥</a><button class="icon-btn edit" onclick="editB({{ $b->id }})">✏️</button><form style="display:inline" method="POST" action="{{ route('admin.testengine.batches.destroy',$b) }}" onsubmit="return confirm('Delete batch?')">@csrf @method('DELETE')<button class="icon-btn delete">🗑️</button></form></td></tr>@endforeach</tbody></table><div class="pagination">{{ $batches->links('vendor.pagination.custom') }}</div></div>
<div class="modal-backdrop" id="addB" style="display:none"><div class="modal" style="width:620px"><div class="modal-header"><b>Create Test Batch</b><span onclick="closeModal('addB')">✕</span></div><form method="POST" action="{{ route('admin.testengine.batches.store') }}">@csrf
@include('admin.test_engine.batch_form')<button class="btn btn-primary" style="margin-top:18px">Save Batch</button></form></div></div>
<div class="modal-backdrop" id="editB" style="display:none"><div class="modal" style="width:620px"><div class="modal-header"><b>Edit Test Batch</b><span onclick="closeModal('editB')">✕</span></div><form id="editBForm" method="POST">@csrf @method('PUT')<label>Batch Title</label><input id="ebTitle" name="title" required><label>Category</label><select id="ebCategory" name="category_id"><option value="">All</option>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select><label>Description</label><textarea id="ebDesc" name="description"></textarea><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><div><label>Price</label><input id="ebPrice" type="number" step="0.01" name="price"></div><div><label>Validity Days</label><input id="ebValidity" type="number" name="validity_days"></div></div><label><input id="ebPaid" type="checkbox" name="is_paid" value="1" style="width:auto"> Paid</label><label>Status</label><select id="ebStatus" name="status"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select><button class="btn btn-primary" style="margin-top:18px">Save Changes</button></form></div></div>
@endsection

@section('scripts')<script>const batchData={@foreach($batches as $b){{ $b->id }}:{title:@json($b->title),category:@json($b->category_id),description:@json($b->description),price:@json($b->price),validity:@json($b->validity_days),paid:{{ $b->is_paid?'true':'false' }},status:@json($b->status)},@endforeach};function editB(id){const b=batchData[id];document.getElementById('editBForm').action='/admin/test-engine/batches/'+id;document.getElementById('ebTitle').value=b.title;document.getElementById('ebCategory').value=b.category||'';document.getElementById('ebDesc').value=b.description||'';document.getElementById('ebPrice').value=b.price;document.getElementById('ebValidity').value=b.validity;document.getElementById('ebPaid').checked=b.paid;document.getElementById('ebStatus').value=b.status;openModal('editB');}</script>@endsection
