@extends('layouts.admin')
@section('title','Test Batch Engine')
@section('content')
<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:18px;"><div><div style="color:#6B7280;font-size:13px;">Dashboard / Test Batch Engine</div><h2 style="margin:4px 0;">Test Batch Engine</h2></div><a class="btn btn-primary" href="{{ route('admin.testengine.batches') }}">＋ Create Test Batch</a></div>
<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:18px;">@foreach([['Total Categories',$stats['categories'],'🗂️'],['Total Questions',$stats['questions'],'📄'],['Total Tests',$stats['tests'],'☷'],['Total Students',$stats['students'],'👥']] as $s)<div class="card"><div style="font-size:25px;">{{ $s[2] }}</div><div style="color:#6B7280;font-size:13px;margin-top:8px;">{{ $s[0] }}</div><div style="font-size:28px;font-weight:700;">{{ $s[1] }}</div></div>@endforeach</div>
<div style="display:grid;grid-template-columns:1.4fr 1fr;gap:18px;margin-bottom:18px;"><div class="card"><div class="card-header"><div class="card-title">Test Overview</div><span class="badge">Last 30 Days</span></div><canvas id="attemptChart" height="110"></canvas></div><div class="card"><div class="card-header"><div class="card-title">Top Performing Tests</div><a href="{{ route('admin.testengine.tests') }}" style="color:#7C3AED;">View All</a></div><table><thead><tr><th>Test</th><th>Attempts</th></tr></thead><tbody>@forelse($topTests as $t)<tr><td>{{ $t->title }}</td><td>{{ $t->attempts_count }}</td></tr>@empty<tr><td colspan="2">No attempts yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="card"><div class="card-header"><div class="card-title">Recent Test Batches</div><a href="{{ route('admin.testengine.batches') }}" style="color:#7C3AED;">View All</a></div><table><thead><tr><th>Batch Title</th><th>Category</th><th>Tests</th><th>Questions</th><th>Validity</th><th>Price</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($recentBatches as $b)<tr><td>{{ $b->title }}</td><td>{{ $b->category->name ?? 'All' }}</td><td>{{ $b->tests_count }}</td><td>{{ $b->tests->sum('question_count') }}</td><td>{{ $b->validity_days }} Days</td><td>₹{{ number_format($b->price,2) }}</td><td>{{ ucfirst($b->status) }}</td><td><a class="btn btn-outline" href="{{ route('admin.testengine.access',$b) }}">Access</a></td></tr>@empty<tr><td colspan="8">No batches created.</td></tr>@endforelse</tbody></table></div>
@endsection
@section('scripts')<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.4/chart.umd.min.js"></script><script>new Chart(document.getElementById('attemptChart'),{type:'bar',data:{labels:@json($labels),datasets:[{label:'Attempts',data:@json($data)}]},options:{plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}});</script>@endsection
