@extends('layouts.admin')
@section('title','Question Management')
@section('content')
<div class="card"><div class="card-header"><div class="card-title">Question Management</div><div style="display:flex;gap:8px"><button class="btn btn-secondary" onclick="openModal('importQ')">CSV Import</button><button class="btn btn-primary" onclick="openModal('addQ')">＋ Add Question</button></div></div>
<form method="GET" style="display:grid;grid-template-columns:1fr 1fr 1fr 2fr auto;gap:8px;margin-bottom:16px"><select name="category_id"><option value="">All Categories</option>@foreach($categories as $c)<option value="{{ $c->id }}" @selected(request('category_id')==$c->id)>{{ $c->name }}</option>@endforeach</select><select name="topic_id"><option value="">All Topics</option>@foreach($topics as $t)<option value="{{ $t->id }}" @selected(request('topic_id')==$t->id)>{{ $t->name }}</option>@endforeach</select><select name="difficulty"><option value="">All Difficulty</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select><input name="search" value="{{ request('search') }}" placeholder="Search questions"><button class="btn btn-primary">Filter</button></form>
<table><thead><tr><th>Question ID</th><th>Question</th><th>Category / Topic</th><th>Difficulty</th><th>Status</th><th>Action</th></tr></thead><tbody>@foreach($questions as $q)<tr><td>{{ $q->id }}</td><td style="max-width:480px">{{ \Illuminate\Support\Str::limit($q->question_text,100) }}</td><td>{{ $q->category->name??'—' }} / {{ $q->topic->name??'—' }}</td><td>{{ ucfirst($q->difficulty) }}</td><td>{{ $q->status?'Active':'Inactive' }}</td><td><button class="icon-btn edit" onclick="editQ({{ $q->id }})">✏️</button><form style="display:inline" method="POST" action="{{ route('admin.testengine.questions.destroy',$q) }}" onsubmit="return confirm('Delete question?')">@csrf @method('DELETE')<button class="icon-btn delete">🗑️</button></form></td></tr>@endforeach</tbody></table><div class="pagination">{{ $questions->links('vendor.pagination.custom') }}</div></div>
<div class="modal-backdrop" id="addQ" style="display:none"><div class="modal" style="width:650px"><div class="modal-header"><b>Add Question</b><span onclick="closeModal('addQ')">✕</span></div><form method="POST" action="{{ route('admin.testengine.questions.store') }}">@csrf
@include('admin.test_engine.question_form', ['prefix'=>''])<button class="btn btn-primary" style="margin-top:18px">Save Question</button></form></div></div>
<div class="modal-backdrop" id="importQ" style="display:none"><div class="modal"><div class="modal-header"><b>Import Questions CSV</b><span onclick="closeModal('importQ')">✕</span></div><p style="color:#6B7280;font-size:13px">Columns: question_text, correct_answer, question_type, option_a, option_b, option_c, option_d, explanation, difficulty, tags</p><form method="POST" enctype="multipart/form-data" action="{{ route('admin.testengine.questions.import') }}">@csrf<input type="file" name="file" accept=".csv,.txt" required><button class="btn btn-primary" style="margin-top:18px">Import</button></form></div></div>
<div class="modal-backdrop" id="editQ" style="display:none"><div class="modal" style="width:650px"><div class="modal-header"><b>Edit Question</b><span onclick="closeModal('editQ')">✕</span></div><form id="editQForm" method="POST">@csrf @method('PUT')<label>Question</label><textarea id="eqText" name="question_text" rows="4" required></textarea><label>Correct Answer</label><input id="eqCorrect" name="correct_answer" required><label>Explanation</label><textarea id="eqExplain" name="explanation" rows="3"></textarea><label>Difficulty</label><select id="eqDifficulty" name="difficulty"><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select><label>Tags</label><input id="eqTags" name="tags"><label>Image URL</label><input id="eqImage" name="image_url" type="url"><label><input id="eqStatus" type="checkbox" name="status" value="1" style="width:auto"> Active</label><input id="eqCategory" type="hidden" name="category_id"><input id="eqTopic" type="hidden" name="topic_id"><input id="eqType" type="hidden" name="question_type"><div id="eqOptions"></div><button class="btn btn-primary" style="margin-top:18px">Save Changes</button></form></div></div>
@endsection

@section('scripts')
<script>
const questionData={@foreach($questions as $q){{ $q->id }}:{text:@json($q->question_text),correct:@json($q->correct_answer),explanation:@json($q->explanation),difficulty:@json($q->difficulty),tags:@json($q->tags),image:@json($q->image_url),status:{{ $q->status?'true':'false' }},category:@json($q->category_id),topic:@json($q->topic_id),type:@json($q->question_type),options:@json($q->options??[])}@if(!$loop->last),@endif @endforeach};
function editQ(id){const q=questionData[id];if(!q)return;document.getElementById('editQForm').action='/admin/test-engine/questions/'+id;document.getElementById('eqText').value=q.text;document.getElementById('eqCorrect').value=q.correct;document.getElementById('eqExplain').value=q.explanation||'';document.getElementById('eqDifficulty').value=q.difficulty;document.getElementById('eqTags').value=q.tags||'';document.getElementById('eqImage').value=q.image||'';document.getElementById('eqStatus').checked=q.status;document.getElementById('eqCategory').value=q.category||'';document.getElementById('eqTopic').value=q.topic||'';document.getElementById('eqType').value=q.type;document.getElementById('eqOptions').innerHTML=(q.options||[]).map(v=>'<input name="options[]" value="'+String(v).replaceAll('"','&quot;')+'" style="margin-top:8px;width:100%;padding:11px 14px;border:1px solid #E5E7EB;border-radius:10px">').join('');openModal('editQ');}
</script>
@endsection
