@extends('layouts.admin')
@section('title','Test Topics')
@section('content')
<div class="card"><div class="card-header"><div class="card-title">Topic Management</div><button class="btn btn-primary" onclick="openModal('addTopic')">＋ Add Topic</button></div><table><thead><tr><th>Topic</th><th>Category</th><th>Status</th><th>Action</th></tr></thead><tbody>@foreach($topics as $t)<tr><td>{{ $t->name }}</td><td>{{ $t->category->name ?? '—' }}</td><td>{{ $t->status?'Active':'Inactive' }}</td><td><button class="icon-btn edit" onclick="editTopic({{ $t->id }},@json($t->name),{{ $t->category_id??'null' }})">✏️</button><form style="display:inline" method="POST" action="{{ route('admin.testengine.topics.destroy',$t) }}" onsubmit="return confirm('Delete topic?')">@csrf @method('DELETE')<button class="icon-btn delete">🗑️</button></form></td></tr>@endforeach</tbody></table><div class="pagination">{{ $topics->links('vendor.pagination.custom') }}</div></div>
<div class="modal-backdrop" id="addTopic" style="display:none"><div class="modal"><div class="modal-header"><b>Add Topic</b><span onclick="closeModal('addTopic')">✕</span></div><form method="POST" action="{{ route('admin.testengine.topics.store') }}">@csrf<label>Category</label><select name="category_id"><option value="">All</option>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select><label>Topic</label><input name="name" required><button class="btn btn-primary" style="margin-top:18px">Save</button></form></div></div>
<div class="modal-backdrop" id="editTopic" style="display:none"><div class="modal"><div class="modal-header"><b>Edit Topic</b><span onclick="closeModal('editTopic')">✕</span></div><form id="editTopicForm" method="POST">@csrf @method('PUT')<label>Category</label><select id="editTopicCategory" name="category_id"><option value="">All</option>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select><label>Topic</label><input id="editTopicName" name="name" required><button class="btn btn-primary" style="margin-top:18px">Save</button></form></div></div>
@endsection
@section('scripts')<script>const topicUpdateUrlTemplate = @json(route('admin.testengine.topics.update', ['topic' => '__TOPIC_ID__']));
function editTopic(id,n,c){document.getElementById('editTopicForm').action=topicUpdateUrlTemplate.replace('__TOPIC_ID__', id);document.getElementById('editTopicName').value=n;document.getElementById('editTopicCategory').value=c??'';openModal('editTopic');}</script>@endsection
